 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ideas", type: :request do
  
  # Idea. As you add validations to Idea, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Idea.create! valid_attributes
      get ideas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      idea = Idea.create! valid_attributes
      get idea_url(idea)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_idea_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      idea = Idea.create! valid_attributes
      get edit_idea_url(idea)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Idea" do
        expect {
          post ideas_url, params: { idea: valid_attributes }
        }.to change(Idea, :count).by(1)
      end

      it "redirects to the created idea" do
        post ideas_url, params: { idea: valid_attributes }
        expect(response).to redirect_to(idea_url(Idea.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Idea" do
        expect {
          post ideas_url, params: { idea: invalid_attributes }
        }.to change(Idea, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post ideas_url, params: { idea: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested idea" do
        idea = Idea.create! valid_attributes
        patch idea_url(idea), params: { idea: new_attributes }
        idea.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the idea" do
        idea = Idea.create! valid_attributes
        patch idea_url(idea), params: { idea: new_attributes }
        idea.reload
        expect(response).to redirect_to(idea_url(idea))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        idea = Idea.create! valid_attributes
        patch idea_url(idea), params: { idea: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested idea" do
      idea = Idea.create! valid_attributes
      expect {
        delete idea_url(idea)
      }.to change(Idea, :count).by(-1)
    end

    it "redirects to the ideas list" do
      idea = Idea.create! valid_attributes
      delete idea_url(idea)
      expect(response).to redirect_to(ideas_url)
    end
  end
end
